# http://pastebin.com/UMEPc0B6
# list of item names
 
wood:
    - WOOD
    - WOOD_2
    - LOG
    - WOOD_STAIRS
    - SPRUCE_WOOD_STAIRS
    - BIRCH_WOOD_STAIRS
    - DARK_OAK_STAIRS
    - JUNGLE_WOOD_STAIRS
    - ACACIA_STAIRS
    - BED
    - STICK
    - WOOD_BUTTON
    - WOOD_AXE
    - WOOD_SWORD
    - WOOD_STEP
    - WOOD_SWORD
    - WOOD_HOE
    - WOOD_PICKAXE
    - WOOD_SPADE
    - TRAP_DOOR
    - SAPLING
    - WOOD_PLATE
    - WOODEN_DOOR
    - WORKBENCH
    - SIGN
    - CHEST
    - TRAPPED_CHEST
    - LADDER
    - JUKEBOX
    - ITEM_FRAME
    - FENCE
    - FENCE_GATE
    - FISHING_ROD
    - BOWL
    - BOOKSHELF
    - BOAT
 
buildingblocks:
    - CLAY
    - COBBLESTONE
    - DIRT
    - GRAVEL
    - ICE
    - PACKED_ICE
    - STONE
    - SAND
    - SANDSTONE
    - STONE
    - GRASS
    - GLASS
    - BONE_BLOCK
    - BOOKSHELF
    - BRICK
    - CLAY
    - CLAY_BRICK
    - CONCRETE
    - CONCRETE_POWDER
    - HAY_BLOCK
    - JUKEBOX
    - JACK_O_LANERN
    - LEAVES
    - LEAVES_2
    - LOG_2
    - MELON_BLOCK
    - MOSSY_COBBLESTONE
    - WOOD
    - NETHER_BRICK
    - MYCEL
    - OBSIDIAN
    - NETHER_WART_BLOCK
    - PRISMARINE
    - PURPUR_BLOCK
    - QUARTZ_BLOCK
    - REDSTONE_BLOCK
    - SNOW_BLOCK
    - LOG

stone:
    - STONE
    - COBBLESTONE
    - BRICK
    - CLAY_BRICK
    - NETHER_BRICK
    - QUARTZ_BLOCK
    - OBSIDIAN
    - COBBLE_WALL
    - COBBLESTONE_STAIRS
    - STONE_SLAB2
    - STEP
    - BRICK_STAIRS
    - CLAY_BRICK_STAIRS
    - NETHER_BRICK_FENCE
    - NETHER_BRICK_STAIRS
    - QUARTZ_STAIRS

mobdrops:
    - STRING
    - SPIDER_EYE
    - WOOL
    - SHULKER_SHELL
    - RAW_BEEF
    - RAW_CHICKEN
    - RAW_FISH
    - RABBIT
    - RABBIT_FOOT
    - RABBIT_HIDE
    - PORK
    - MAGMA_CREAM
    - GRILLED_PORK
    - GHAST_TEAR
    - GUNPOWDER
    - EGG
    - DRAGON_EGG
    - BONE

food:
    - CAKE
    - BREAD
    - COCOA
    - COOKIE
    - COOKED_BEEF
    - COOKED_CHICKEN
    - COOKED_FISH
    - COOKED_MUTTON
    - COOKED_RABBIT
    - RAW_BEEF
    - RAW_CHICKEN
    - RAW_FISH
    - RABBIT
    - RABBIT_FOOT
    - RABBIT_HIDE
    - PORK
    - EGG

minerals:
    - DIAMOND
    - EMERALD
    - IRON_BAR
    - GOLD_BAR
    - COAL
    - LAPIS_BLOCK
    - INK_SACK
    - COAL_BLOCK
    - DIAMOND_BLOCK
    - EMERALD_BLOCK
    - GOLD_BLOCK

tools:
    - WOOD_AXE
    - WOOD_HOE
    - WOOD_PICKAXE
    - WOOD_SPADE
    - WOOD_SWORD
    - STONE_AXE
    - STONE_HOE
    - STONE_PICKAXE
    - STONE_SPADE
    - STONE_SWORD
    - BOW
    - IRON_AXE
    - IRON_CHESTPLATE
    - IRON_HELMET
    - IRON_HOE
    - IRON_LEGGINGS
    - IRON_PICKAXE
    - IRON_SPADE
    - IRON_SWORD
    - LEATHER_BOOTS
    - LEATHER_CHESTPLATE
    - LEATHER_HELMET
    - LEATHER_LEGGINGS
    - DIAMOND_AXE 
    - DIAMOND_BARDING 
    - DIAMOND_BLOCK 
    - DIAMOND_BOOTS 
    - DIAMOND_CHESTPLATE 
    - DIAMOND_HELMET 
    - DIAMOND_HOE 
    - DIAMOND_LEGGINGS 
    - DIAMOND_PICKAXE 
    - DIAMOND_SPADE 
    - DIAMOND_SWORD 
    - GOLD_AXE 
    - GOLD_BARDING 
    - GOLD_BOOTS 
    - GOLD_CHESTPLATE 
    - GOLD_HELMET 
    - GOLD_HOE 
    - GOLD_INGOT 
    - GOLD_LEGGINGS 
    - GOLD_NUGGET 
    - GOLD_ORE 
    - GOLD_PICKAXE
    - GOLD_RECORD 
    - GOLD_SPADE 
    - GOLD_SWORD  
    
dirt:
    - SAND
    - GRAVEL
    - DIRT
    - SOIL
    - GRASS
